mappings:
  ColorPaletteField: Fromholdio\ColorPalette\Fields\ColorPaletteField
  ColorPaletteField_Readonly: Fromholdio\ColorPalette\Fields\ColorPaletteField_Readonly
  GroupedColorPaletteField: Fromholdio\ColorPalette\Fields\GroupedColorPaletteField
  GroupedColorPaletteField_Readonly: Fromholdio\ColorPalette\Fields\GroupedColorPaletteField_Readonly
